//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstuctionManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConstructionEntities2 : DbContext
    {
        public ConstructionEntities2()
            : base("name=ConstructionEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_expensemaster> tbl_expensemaster { get; set; }
        public DbSet<tbl_expensetype> tbl_expensetype { get; set; }
        public DbSet<tbl_itemmaster> tbl_itemmaster { get; set; }
        public DbSet<tbl_materialissue> tbl_materialissue { get; set; }
        public DbSet<tbl_project> tbl_project { get; set; }
        public DbSet<tbl_purchase> tbl_purchase { get; set; }
        public DbSet<tbl_role> tbl_role { get; set; }
        public DbSet<tbl_unit> tbl_unit { get; set; }
        public DbSet<tbl_user> tbl_user { get; set; }
        public DbSet<tbl_stock> tbl_stock { get; set; }
    }
}
