//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstuctionManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_itemmaster
    {
        public tbl_itemmaster()
        {
            this.tbl_materialissue = new HashSet<tbl_materialissue>();
            this.tbl_purchase = new HashSet<tbl_purchase>();
        }
    
        public int product_id { get; set; }
        public string unit { get; set; }
        public string item { get; set; }
        public string item_code { get; set; }
        public Nullable<int> project_id { get; set; }
    
        public virtual tbl_project tbl_project { get; set; }
        public virtual ICollection<tbl_materialissue> tbl_materialissue { get; set; }
        public virtual ICollection<tbl_purchase> tbl_purchase { get; set; }
        public virtual tbl_stock tbl_stock { get; set; }
    }
}
