//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstuctionManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_purchase
    {
        public Nullable<int> product_id { get; set; }
        public int purchase_id { get; set; }
        public string invoice { get; set; }
        public string supplier { get; set; }
        public string company { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
        public Nullable<decimal> purchase_rate { get; set; }
        public Nullable<int> project_id { get; set; }
    
        public virtual tbl_itemmaster tbl_itemmaster { get; set; }
        public virtual tbl_project tbl_project { get; set; }
    }
}
