//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstuctionManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_user
    {
        
        public int user_id { get; set; }
        public string username { get; set; }
        [Required(ErrorMessage = "Please Enter username!")]
        public string password { get; set; }
        [Required(ErrorMessage = "Please Enter Password!")]
        public Nullable<int> role_id { get; set; }
        public virtual tbl_role tbl_role { get; set; }



        public string LoginErrorMessage { get; set; }
    }
}
