//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstuctionManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_project
    {
        public tbl_project()
        {
            this.tbl_expensemaster = new HashSet<tbl_expensemaster>();
            this.tbl_itemmaster = new HashSet<tbl_itemmaster>();
            this.tbl_materialissue = new HashSet<tbl_materialissue>();
        }
    
        public int project_id { get; set; }
        public string project_name { get; set; }
        public Nullable<decimal> e_price { get; set; }
        public Nullable<System.DateTime> e_time { get; set; }
    
        public virtual ICollection<tbl_expensemaster> tbl_expensemaster { get; set; }
        public virtual ICollection<tbl_itemmaster> tbl_itemmaster { get; set; }
        public virtual ICollection<tbl_materialissue> tbl_materialissue { get; set; }
        public virtual tbl_purchase tbl_purchase { get; set; }
    }
}
