//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstuctionManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_stock
    {
        public int product_id { get; set; }
        public Nullable<decimal> quantity { get; set; }
    
        public virtual tbl_itemmaster tbl_itemmaster { get; set; }
    }
}
